name: Terraform Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure Azure Credentials
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: echo "Azure credentials set."

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Plan
        run: terraform plan -out=tfplan
          -var "client_id=${{ secrets.ARM_CLIENT_ID }}" \
          -var "client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
          -var "tenant_id=${{ secrets.ARM_TENANT_ID }}" \
          -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
        working-directory: terraform/

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Only apply on the main branch
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/
